---
:appifier:
  :production: {}
  :staging: {}
  :development: {}
  :test: {}
  :default:
    :test: 'Romain'
    :exit_cases:
      :not_root: 
        :message: This operation need to be run as root (use sudo or rvmsudo)
        :code: 10
      :options_incompatibility:
        :message: Options incompatibility
        :code: 40
      :service_dependence_missing:
        :message: Appifier Service dependence missing
        :code: 60
      :config_required:
        :message: Specific configuration required
        :code: 30
      :setup_error:
        :message: Setup terminated unsuccessfully
        :code: 25
      :setup_success:
        :message: Setup terminated successfully
        :code: 0
      :sanitycheck_error:
        :messagee: Sanitycheck terminated unsuccessfully
        :code: 20
      :sanitycheck_success:
        :message: Sanitycheck terminated successfully
        :code: 0
      :configuration_error:
        :message: Configuration Error
        :code: 50
  
  
         # global
      :quiet_exit:
        :code: 0
      :error_exit:
        :code: 99 
        :message: Operation failure
  
         # events
      :interrupt:
        :message: User operation interrupted
        :code: 33
  
      # request
      :not_found:
        :message: Object not found
        :code: 44
      :already_exist:
        :message: Object already exist
        :code: 48

      # daemon
      :status_ok:
        :message: Status OK
        :code: 0
      :status_ko:
        :message: Status KO
        :code: 31


